### ISSUE TITLE
Inquiry about code 

### ISSUE THREAD

**Issue by JingfengYang** [jacobandreas/geca#5]
Hi Jacob,

I'm thinking you are reusing Robin Jia's code for geoquery logic experiments, (e.g. code=../../../3p/jia/src
 in https://github.com/jacobandreas/geca/blob/master/exp/semparse_geo_logic/query_retrieval_jia/run.sh ). I tried to use their code here https://worksheets.codalab.org/worksheets/0x50757a37779b485f89012e4ba03b6f4f/ . But it seems that you modified some of their code, right? For instance, there is no argument "--jda_augment " in their main.py scripts. Would you mind also sharing your modified code for this part?

Thanks,
Jingfeng

**Comment by jacobandreas** [comment]
Sorry for the incredibly slow reply here! I spent some time looking around, but unfortunately it seems like the modified version of their code was on a Berkeley machine that I know longer have access to. IIRC the only thing the --jda_augment flag did was grab the output of GECA and concatenate it to the base dataset, so should be really easy to implement if you still need it.

Also: https://arxiv.org/abs/2112.07610 is basically the same idea as jia+liang with better grammar induction (and works super well), so that's probably the baseline you want to compare to where applicable.
